language: bash
services: docker

matrix:
  fast_finish: true

env:
  - VERSION=12
  - VERSION=12 VARIANT=alpine
  - VERSION=11
  - VERSION=11 VARIANT=alpine
  - VERSION=10
  - VERSION=10 VARIANT=alpine
  # - VERSION=9
  - VERSION=9 VARIANT=alpine

before_script:
  - cd "${VERSION}/${VARIANT}"
  - IMAGE="igabriele/postgresql-pgjwt:${VERSION}${VARIANT:+-${VARIANT}}"
script:
  - docker build -t "${IMAGE}" .

before_deploy:
  - |
    if [ "${PWD##*/}" = "alpine" ]; then
      cd ../..
    else
      cd ..
    fi
  - docker images
deploy:
  provider: script
  script: ./scripts/ci/push_to_docker.sh
  skip_cleanup: true
  on:
    branch: master
    repo: ivangabriele/postgresql-pgjwt

# Limit branches builds to "master" one:
branches:
  only:
    - master

notifications:
  email:
    on_failure: change
    on_success: never
